In [1]:
import numpy as np

In [2]:
## create a numpy array 'arr'  of integers 0 to 5 and print its data type.
arr=np.array((0,1,2,3,4,5))

In [3]:
arr.dtype

dtype('int64')

In [4]:
## 2.create a numpy array "arr" check its data type is float 64.
arr=np.array([1.5,2.6,3.7])

In [ ]:
arr.dtype

dtype('float64')

In [5]:
## 3.create numpy array "arr" with data type of complex 128 containing three complex numbers
arr=np.array([3+4j,4+5j,5+6j])

In [6]:
## 4.convert existing numpay array "arr" of integer to float 32 data type
arr=np.array([1,2,3,4,5])



In [7]:
arr.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
##5given a numpy array  "arr" float64 data type,convert it to float 32 to reduce decimal precesion.
arr=np.array([1.,2.,3.,4.],dtype=np.float64)

In [9]:
arr.astype(np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [10]:
## 6 write a function array attribute that  takes numpy array as input and return its shape,size and data type
def array_attribute(arr):
  print(f"shpae is {arr.shape}")
  print(f"size is {arr.size}")
  print(f"data type is {arr.dtype}")

In [11]:
array_attribute(arr=np.array([1,2,3,4,5]))

shpae is (5,)
size is 5
data type is int64


In [12]:
## 7. create a function array_dimension that takes numpy array as input and return its dimensionality.
def array_dimension(arr):
  print(f"dimensionality is {arr.ndim}")



In [13]:
array_dimension(arr=np.array([[1,2,3,],[4,5,6]]))

dimensionality is 2


In [14]:
## 8. design a function item_size_info that takes a numpy array as input and return item size and the total size in bytes.
def item_size_info(arr):
  print(f"item size is {arr.itemsize}")
  print(f"total size is {arr.nbytes}")



In [15]:
item_size_info(arr=np.array([[1,2,3,],[4,5,6]]))

item size is 8
total size is 48


In [16]:
## 9.create a function array _stride tha takes numpy array as input and return the stride of array.
def array_stride(arr):
  print(arr)
  print(f"stride is {arr.strides}")

In [17]:
array_stride(arr=np.array([[1,2,3,],[4,5,6]]))

[[1 2 3]
 [4 5 6]]
stride is (24, 8)


In [18]:
 ##10.design a function shape_stride_relationship that takes numpay array as input and return the shape and stride of the array.
 def shape_stride_relationship(arr):
  print(arr)
  print(f"shape is {arr.shape}")
  print(f"stride is {arr.strides}")


In [19]:
shape_stride_relationship(arr=np.array([[1,2,3,],[4,5,6]]))

[[1 2 3]
 [4 5 6]]
shape is (2, 3)
stride is (24, 8)


In [20]:
## 11. create a function create_zeros_array  that takes an integer n as input return a numpy array of zeros element with n element
def create_zeros_array(n):
  return np.zeros(n)

In [ ]:
create_zeros_array((4))


In [ ]:
##12. wrtie a function create ones matrix that takes integers rows and cols as input and generate 2d numpay array filled with ones of size rows x cols.
def create_ones_matrix(rows,cols):
  return np.ones((rows,cols))

In [ ]:
create_ones_matrix(rows=4,cols=3)

In [ ]:
##13.write a function generate_range_array that takes three inputs start,stop and step as argument and create numpy array with range starting
## start form start ending at stop(exculsive),with specified step.
def generate_range_array(start,stop,step):
  return np.arange(start,stop,step)


In [ ]:
generate_range_array(start=2,stop=10,step=2)

In [ ]:
##14.design function generate_linear_space that takes two float start,stop,and integer num as argument and generate a numpy array with num equally spaced
## value between start and stop (inclusive)
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)

In [ ]:
generate_linear_space(start=3.4,stop=12.4,num=3)

array([ 3.4,  7.9, 12.4])

In [ ]:
## 15. create a function create_Identity_matrix that takes  an integer n as input and generate a square identity of size of size n*n using numpy.eye
def create_identity_matrix(n):
  return np.eye(n)


In [ ]:
create_identity_matrix(n=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
##16. write a function that takes a pythoon list and convert into numpy array
def list_to_array(lis):
  return np.array(lis)

In [ ]:
list_to_array(lis=[1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
## 17. create a numpy array and demonstrate the use of numpy.view to create a new array object with the some data.
arr=np.array([1,2,3,4,5,6,7,8])
arr1=arr.view()



In [21]:
arr1[0]=10
print("oringnal array is",arr)
print("view array is ",arr1)

NameError: name 'arr1' is not defined

In [24]:
# # 18. write a function that takes two numpy array and concatenate them horizonatally using numpy concatenate
def concatenate_array(arr1,arr2):
  return np.concatenate((arr1,arr2),axis=0)

In [25]:
concatenate_array(arr1=np.array((1,2,3,4)),arr2=np.array((5,6,7,8)))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
##19. create a numpy array with different shape and concatenate them horizonatally using numpy. conatenate.
def concatenate(arr1,arr2):
  return  np.concatenate((arr1,arr2),axis=0)

In [27]:
concatenate(arr1=np.array([1,2,3,4]),arr2=np.array([33,44,55]))

array([ 1,  2,  3,  4, 33, 44, 55])

In [28]:
##20. write a function that vertically stacks multiple numpy array given a list.
def vertical_stack(arr):
  return np.vstack(arr)

In [29]:
vertical_stack(arr=[(np.array([1,2,3,4]),np.array([33,44,55,66]))])

array([[ 1,  2,  3,  4],
       [33, 44, 55, 66]])

In [30]:
## 21. write a pythoon function using numpy array to create an array  of integers wihiin specified range(inculsive)
def array_num(start,stop):
  return np.arange(start,stop+1)

In [31]:
array_num(start=2,stop=10)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
##22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive).
def generate_array(start,stop):
  return np.linspace(start,stop,10)

In [33]:
generate_array(start=0,stop=1)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
## 23. write a pythoon function using numpay array to create an arary of 5 logarithmcally spacel value between 1 and 1000(inclusiv))
def generate_array(start,stop,num):
  return np.logspace(start,stop,num)

In [34]:
generate_array(1,1000,5)

TypeError: generate_array() takes 2 positional arguments but 3 were given

In [35]:
## 24. create pandas dataframe using numpay array that contain 5 rows and 3 coloumns where the value are random integer between 1 to 100
import pandas as pd
def create_dataframe(rows,cols):
  return pd.DataFrame(np.random. randint(1,100,size=(rows,cols)))




In [36]:
create_dataframe(rows=5,cols=3)

0   1   2
0  26  86  38
1  91  61  10
2  68  47   9
3  97  65  11
4  70  77  75

In [37]:
## 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
## with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negative(df):
  df["A"]=df["A"].apply(lambda x:0 if x<0 else x)
  return df


In [38]:
import pandas as pd
data = {'A': [1, -2, 3, -4, 5], 'B': [6, 7, -8, 9, 10]}
df = pd.DataFrame(data)
replace_negative(df)


A   B
0  1   6
1  0   7
2  3  -8
3  0   9
4  5  10

In [39]:
## 26.## acess third element given numpay array
arr=np.array([10,20,30,40,50])
arr[3]

40

In [40]:
## retrieve the element at index(1,2) form the 2d numpy array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr_2d[1][2]

6

In [43]:
## 28.using boolean indexing,extract element greater than 5 from given numpy array
arr=np.array([3,8,2,10,5,7])
arr

array([ 3,  8,  2, 10,  5,  7])

In [44]:
arr[arr>5]

array([ 8, 10,  7])

In [45]:
## 29.perform basis slicing to extract element  from index 2 to 5(inclusive) from the given numpay array.
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[2:6]

array([3, 4, 5, 6])

In [46]:
## 30 slice 2d numpay array to extract sub-array[[2,3]],[[5,6]] from the given numpay array.
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
arr_2d[0:2,1:3] ,arr_2d


(array([[2, 3],
        [5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [48]:
## 31. wrtie a numpay function to extract element in specific order form the given 2d array based on indices
## provided in another numpay array
def extract_elements(arr_2d,indices):
  return arr_2d[tuple(indices.T)]



In [49]:
extract_elements(arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]]),indices=np.array([[0,2],[2,0],[1,2]]))

array([3, 7, 6])

In [50]:
## 32.create a numpay function that filter the element greather than threshold from given  1d array using boolean indexing
def filter_elements(arr,threshold):
  return arr[arr>threshold]

In [51]:
filter_elements(np.array([1,2,3,4,5,6,7,8,9,10,11]),threshold=5)

array([ 6,  7,  8,  9, 10, 11])

In [52]:
import numpy as np
##33.develop a numpay function that extract specific elements from 3d array using indices provided in three seperate array for each dimension
def extract_elements(arr_3d,indices_x,indices_y,indices_z):
  print(arr_3d)
  return arr_3d[indices_x,indices_y,indices_z]

In [53]:
extract_elements(arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]]),indices_x=np.array([0]),indices_y=np.array([1]),indices_z=np.array([2]))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([6])

In [54]:
##34. write a numpay function that return elements form an array where both condition are satisfied using boolean indexing.
def filter_elements(arr,condition1,condition2):
  return arr[(arr>condition1)& (arr<condition2)]

In [55]:
filter_elements(arr=np.array([1,2,3,4,5,6,7,8,9]),condition1=3,condition2=9)

array([4, 5, 6, 7, 8])

In [56]:
## 35. create a numpay function that extracts  elements form 2d array using row and columns indcies provided in seperate array
def extract_elements(arr_2d,row_indices,col_indices):
  print(arr_2d)
  return arr_2d[row_indices,col_indices]

In [57]:
extract_elements(arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]]),row_indices=np.array([0,2]),col_indices=np.array([0,2]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 9])

In [58]:
##36. given an array of shape(3,3),add a scalar value of 5 to each elements using numpay broadcasting.
def add_scalar(arr1,scalar):
  return arr1+scalar

In [59]:
add_scalar(arr1=np.array([[1,2,3],[4,5,6],[7,8,9]]),scalar=5)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [60]:
## 37.consider two array of shape (1,3) and array shape (3,4).multiply each row of arr2 by the corresponding elements in arr1
## using numpay broadcasting.
def multiply_rows(arr1,arr2):
  arr1=arr1.reshape(3,1)
  return arr1*arr2

In [61]:
multiply_rows(arr1=np.array([[1,2,3]]),arr2=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]]))

array([[ 1,  2,  3,  4],
       [ 8, 10, 12, 14],
       [24, 27, 30, 33]])

In [62]:
## 38.given 1d array arr1 of shape (1,4) and a 2d array of shape (4,3), add arr1 to each row of arr2 using numpay bordcasting.
def add_rows(arr1,arr2):

  return arr1+arr2


In [63]:
add_rows(arr1=np.array([1,2,3,4]),arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]))

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [64]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [65]:
import numpy as np
## 39. consider two array  arr1 of shape(3,1) and array shape(1,3) add these two array numpay broacasting
def add_arrays(arr1,arr2):
  return arr1+arr2


In [66]:
add_arrays(np.array([[1],[2],[3]]),arr2=np.array([4,5,6]))

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [67]:
##40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
## broadcasting. Handle the shape incompatibility
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 20], [30, 40]])
arr2_reshaped=arr2[:,np.newaxis,:]
result=arr1[:,:,np.newaxis]*arr2_reshaped
print(result)



[[[ 10  20]
  [ 20  40]
  [ 30  60]]

 [[120 160]
  [150 200]
  [180 240]]]


In [68]:
## 41.calculate coloumn wise mean  for the given array
def column_wise_mean(arr):
  print(arr)
  return np.mean(arr,axis=0)

In [69]:
column_wise_mean(arr=np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


array([2.5, 3.5, 4.5])

In [70]:
## 42.find maxmium value in each row of the given array
def max_value(arr):
  return np.max(arr,axis=1)


In [71]:
max_value(arr=np.array([[1,2,3],[4,5,6]]))

array([3, 6])

In [72]:
## 43.for the given array find indices  of maximum value in each column
def max_value(arr):
  print(arr)
  return np.max(arr,axis=0)


In [73]:
max_value(arr=np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


array([4, 5, 6])

In [202]:
## 44.for the given array,apply custom function to calculate moving sum along rows
def moving_sum(arr,window_size):
  result=[]
  for i in arr:
    row_result=[]
    for j in range(len(i)-window_size+1):
      row_result.append(np.sum(i[j:j+window_size]))
    result.append(row_result)
  return np.array(result)

In [203]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
window_size = 3
moving_sum(arr, window_size)


array([[ 6,  9, 12],
       [21, 24, 27]])

In [75]:
## 45. in the given array.check if all elements in each column are even.
def check_even(arr):
  print(arr)
  return np.all(arr%2==0,axis=0)

In [76]:
check_even(arr=np.array([[2,4,6],[3,5,7]]))

[[2 4 6]
 [3 5 7]]


array([False, False, False])

In [77]:
## 46.given a numpy array  arr,reshape it into matrix of dimension m rows and n coloumns.return the reshaped matrix
def reshape_array(original_array,m,n):
  print(original_array)
  return np.matrix(original_array.reshape(m,n))

In [78]:
reshape_array(original_array=np.array([1,2,3,4,5,6]),m=3,n=2)

[1 2 3 4 5 6]


matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [79]:
## 47.create a function that takes a matrix as a input and return the flattened array
def flatten_array(input_matrix):
  return np.array(input_matrix.flatten())

In [80]:
flatten_array(input_matrix=np.matrix([[1,2,3],[4,5,6]]))

array([[1, 2, 3, 4, 5, 6]])

In [81]:
## 48.write a function that concatenate two given array along specifed axis
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [82]:
np.concatenate((array1,array2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [83]:
## 49. Create a function that splits an array into multiple sub-arrays along a specified axis
def split_array(original_array,indices,axis):
  return np.split(original_array,indices,axis)

In [84]:
split_array(original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),indices=3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [85]:
## 50.write a functiion that inserts and then deletes elements from given array at specified indices
original_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(original_array)
arr1=np.delete(original_array,[1,3])
print("modified_array",np.insert(arr1,[2,4],[10,11]))


[ 1  2  3  4  5  6  7  8  9 10]
modified_array [ 1  3 10  5  6 11  7  8  9 10]


In [86]:
import random
##51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
## Perform element-wise addition between `arr1` and `arr2`.
arr1=np.random.randint(1,10,size=(3,3))
arr2=np.random.randint(1,10,size=(3,3))
arr1
arr2
arr1+arr2

array([[ 9,  8, 12],
       [15, 13, 13],
       [11, 15, 13]])

In [99]:
## 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
##from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr2=np.arange(1,11,1)
arr1=np.arange(10,0,-1)

In [101]:
arr1-arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [104]:
## 53.53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
## Perform element-wise multiplication between `arr1` and `arr2
arr1=np.random.randint(1,6,size=(5))
arr2=np.array([1,2,3,4,5])
arr1*arr2



array([ 2, 10, 15,  8, 10])

In [105]:
##54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
## to 5. Perform element-wise division of `arr1` by `arr2`.
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)
arr1/arr2

array([2., 2., 2., 2., 2.])

In [106]:
##55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
## reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1=np.arange(1,6,1)
arr2=np.arange(5,0,-1)
arr1**arr2

array([ 1, 16, 27, 16,  5])

In [107]:
# # 56. Write a function that counts the occurrences of a specific substring
# within a NumPy array of strings.
arr = np.array(['hello ', 'world', 'hello', 'numpy', 'hello'])
occurrences=np.char.count(arr,'hello')
print(np.sum(occurrences))

3


In [108]:
import numpy as np
## 57. Write a function that extracts uppercase characters from a NumPy array of strings.
def extract_uppercase_char(arr):
   uppercase_chars = [char for string in arr for char in string if char.isupper()]
   return np.array(uppercase_chars)

In [109]:
extract_uppercase_char(arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']))

array(['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T'], dtype='<U1')

In [110]:
##58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
np.char.replace(arr,"apple","mango")

array(['mango', 'banana', 'grape', 'pinemango'], dtype='<U9')

In [111]:
59.## Write a function that concatenates strings in a NumPy array element-wise
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
np.char.add(arr1,arr2)


array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [112]:
## 60. Write a function that finds the length of the longest string in a NumPy array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
np.max(np.char.str_len(arr))

9

In [113]:
## 61.61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
##mstandard deviation of the dataset using NumPy's functions
import numpy as np
arr=np.random.randint(1,1000,size=(100))
print(arr)
print("mean",np.mean(arr))
print("median",np.median(arr))
print("variance",np.var(arr))
print("standard",np.std(arr))


[645 482  28 705 236 118 866 498 407 551 666 881 155 480 179 411 756 683
 950 180 442 994 347 584 867 234 438 640 646 608 831 129 722 822 138 788
 401  18 163 658 234 979 559 670 830 522 235 268 880 548  74 707 436 822
 234 688 626 354 640 774 246 156 263 331 132 368 166 630 912 156 469  49
 536 798 989 454  27 498 917 790 782 231 483 491 363 281   2 204 384 299
 111 709 119 771 633 739  57 152  94 251]
mean 474.7
median 481.0
variance 77027.99
standard 277.53916840691153


In [114]:
## 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
## dataset.
arr1=np.random.randint(1,100,size=(50))
print(arr1)
print(np.percentile(arr1,25))
print(np.percentile(arr1,75))

[76 61 76  1  1 25 12  1 90 52 16 88 93 70  3 63 20 26 74 75 94 99 54 28
 95 75 66 62 64 94 50 68 45 37 67 94 56  7 10 13 70 77  9 43 82 89 43 46
 24 75]
25.25
75.75


In [129]:
##63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
## arrays using NumPy's `corrcoef` function
arr1=np.array([1,2,3,4,5])
arr2=np.array([0,15,30,45,60])
np.corrcoef(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

In [130]:
##64. Create two matrices and perform matrix multiplication using NumPy's `dot` function
arr1=np.matrix([[1,2,3],[4,5,6 ]])
arr2=np.matrix([[7,8,9],[10,11,12],[1,2,3]])
np.dot(arr1,arr2)

matrix([[ 30,  36,  42],
        [ 84,  99, 114]])

In [131]:
##65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
## percentiles along with the first and third quartiles.
arr=np.array(np.random.randint(10,1000,size=(50)))
print(arr)
print(np.percentile(arr,10))
print(np.percentile(arr,50))
print(np.percentile(arr,90))

[943 660 668 461 147 810 853 855 800 807 193 443 954 789 615 585 700 889
 983 963 585 785 226 552 358 110  13 904 765 926 242 106 692 205 128 701
 686 814 544 546 482 944 211 474 244 201 569 767 110 313]
145.1
600.0
927.7


In [132]:
##66. Create a NumPy array of integers and find the index of a specific element.
arr=np.array(np.linspace(1,10,10))
print(arr)
np.where(arr==4)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


(array([3]),)

In [133]:
##67. Generate a random NumPy array and sort it in ascending order
arr=np.random.randint(1,100,size=(10))
print(arr)
np.sort(arr)


[45  7 79 42 28 94 90 60 30 10]


array([ 7, 10, 28, 30, 42, 45, 60, 79, 90, 94])

In [134]:
## 68. Filter elements >20  in the given NumPy array.
arr=np.array([12,25,6,42,8,30])
arr[arr>20]

array([25, 42, 30])

In [135]:
##69. Filter elements which are divisible by 3 from a given NumPy array
arr=np.array([1,5,8,12,15])
arr[arr%3==0]

array([12, 15])

In [136]:
##70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20) &(arr<=40)]

array([20, 30, 40])

In [137]:
##71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

In [150]:
##72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
import struct
arr = np.array([78, 55, 500], dtype=np.int32)
new_arr=np.frombuffer(struct.pack("<"+"i" * len(arr),*arr),dtype=np.int32)
print("orignal",arr)
print("byte_swap",new_arr)
print(arr.tobytes())
print(new_arr.tobytes())

orignal [ 78  55 500]
byte_swap [ 78  55 500]
b'N\x00\x00\x007\x00\x00\x00\xf4\x01\x00\x00'
b'N\x00\x00\x007\x00\x00\x00\xf4\x01\x00\x00'


In [161]:
##73.For the given NumPy array, swap its byte order without modifying the original array using
## newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.view(arr.dtype.newbyteorder())
print("orginal array",arr)
print("byte swapped array",swapped_arr)


orginal array [1 2 3]
byte swapped array [16777216 33554432 50331648]


In [160]:
##74. For the given NumPy array and swap its byte order conditionally based on system endianness using
## newbyteorder()`
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
if sys.byteorder=="little":
   swapped_arr=arr.view(arr.dtype.newbyteorder('big'))
else:
  swapped_arr=arr
print("original array",arr)
print("byte_swapped_array",swapped_arr)




original array [1 2 3]
byte_swapped_array [16777216 33554432 50331648]


In [204]:
##75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
## attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    if sys.byteorder != arr.dtype.byteorder:
        print("Byte swapping is necessary")
    else:
        print("Byte swapping is not necessary")
elif arr.dtype.byteorder != sys.byteorder:
    print("Byte swapping is necessary")
else:
    print("Byte swapping is not necessary")


Byte swapping is necessary


In [205]:
import numpy as np
import random
##76.76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
##an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1=np.arange(1,11,1)
copy_arr=arr1.copy()
print("arr1",arr1)
print("copy_arr1",copy_arr)
copy_arr[0]=100
print(" change in copy arr",copy_arr)
print("arr1",arr1)



arr1 [ 1  2  3  4  5  6  7  8  9 10]
copy_arr1 [ 1  2  3  4  5  6  7  8  9 10]
 change in copy arr [100   2   3   4   5   6   7   8   9  10]
arr1 [ 1  2  3  4  5  6  7  8  9 10]


In [151]:
import random
##77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
## the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix=np.random.randint(1,20,size=(3,3))
print("matrix",matrix)
view_slice=matrix[1:,:2]
view_slice[0,0]=100
print("matrix",matrix)



matrix [[12 12  9]
 [ 5 16 13]
 [11  9 13]]
matrix [[ 12  12   9]
 [100  16  13]
 [ 11   9  13]]


In [152]:
##78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
## view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a
array_a=np.arange(1,13,1).reshape(4,3)
print(array_a)
view_b=array_a[1:,:2]
view_b+=5
print(array_a)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 9 10  6]
 [12 13  9]
 [15 16 12]]


In [153]:
##79 Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
##  of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
## reflects changes in the original `orig_array
orig_array=np.arange(1,9,1).reshape(2,4)
print("orig_array",orig_array)
reshaped_view=orig_array.reshape(4,2)
reshaped_view[0,1]=500
print("orig_array",orig_array)



orig_array [[1 2 3 4]
 [5 6 7 8]]
orig_array [[  1 500   3   4]
 [  5   6   7   8]]


In [154]:
##80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
## elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data
data=np.random.randint(1,50,size=(3,4))
data_copy=data[data>5].copy()
data_copy[0]=200
print("data copy",data_copy)
print( "data",data)


data copy [200  32  38  30  16  11  12  33  12  24  32   6]
data [[18 32 38 30]
 [16 11 12 33]
 [12 24 32  6]]


In [155]:
## 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
## operations between them.
a=np.matrix(np.random.randint(1,50,size=(3,4)))
b=np.matrix(np.random.randint(1,50,size=(3,4)))
print("a+b",a+b)
print("a-b",a-b)


a+b [[62 30 62 42]
 [45 80 13 44]
 [37 46 28 37]]
a-b [[ 10  16  24  32]
 [-29   0   5  34]
 [  9 -36   4  13]]


In [156]:
##82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication
c=np.matrix([[1,2],[3,4],[5,6]])
d=np.matrix([[7,8,9,10],[11,12,13,14]])
c@d

matrix([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])

In [157]:
##83. Create a matrix `E` and find its transpose.
E=np.matrix([[7,8,9,10],[11,12,13,14]])
print(E)
print(E.T)


[[ 7  8  9 10]
 [11 12 13 14]]
[[ 7 11]
 [ 8 12]
 [ 9 13]
 [10 14]]


In [158]:
## 84. Generate a square matrix `F` and compute its determinant.
e=np.matrix([[7,8,9],[11,12,13],[15,16,17]])
np.linalg.det(e)



0.0

In [159]:
## 85. Create a square matrix `G` and find its inverse.
e=np.matrix([[7,8,9],[11,12,13],[15,16,18]])
np.linalg.inv(e)


matrix([[-2.00000000e+00,  9.47390314e-16,  1.00000000e+00],
        [ 7.50000000e-01,  2.25000000e+00, -2.00000000e+00],
        [ 1.00000000e+00, -2.00000000e+00,  1.00000000e+00]])